### ISSUE TITLE
issue with POP segue when using UINavigationController

### ISSUE THREAD

**Issue by shahimclt** [nathanwhy/HYAwesomeTransition#1]
The docs are done for present segue, but when I tried to use it on a Push segue, the Pop was misbehaving and going back to a blank screen. I have traced the issue to line 231 in HYAwesomeTransition.m : 

>    [toVC.view removeFromSuperview];

**Comment by nathanwhy** [comment]
You are right. It also don't need to do in dismiss segue.
I fix it. Thanks a lot.
